version: "3.4"
services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "9050:9050" # SOCKS proxy
      - "5353:5353" # DNS
      - "9051:9051" # Control port
